from pathlib import Path
import re

P = Path(__file__).with_name('TruckBox_RevA.kicad_pcb')
s = P.read_text(encoding='utf-8')

# USB-C production cleanup v4.
# This pass follows v3 and replaces only the local service-USB / right-edge
# routing. It keeps the validated CAN, power, storage and GNSS source routing.
# All new signal tracks obey the board's 0.20 mm minimum and all signal vias
# use the project's proven 0.55 / 0.30 mm geometry.
net_id = {name: int(i) for i, name in re.findall(r'\(net\s+(\d+)\s+"([^"]+)"\)', s)}
id_net = {i: name for name, i in net_id.items()}


def balanced_block(text, start):
    depth = 0
    in_q = False
    esc = False
    for j in range(start, len(text)):
        c = text[j]
        if in_q:
            if esc:
                esc = False
            elif c == '\\':
                esc = True
            elif c == '"':
                in_q = False
            continue
        if c == '"':
            in_q = True
        elif c == '(':
            depth += 1
        elif c == ')':
            depth -= 1
            if depth == 0:
                return j + 1
    raise RuntimeError('unterminated s-expression')


def ref_marker_pos(text, ref):
    hits = []
    for marker in (f'(property "Reference" "{ref}"', f'(fp_text reference "{ref}"'):
        p = text.find(marker)
        if p >= 0:
            hits.append(p)
    return min(hits) if hits else -1


def remove_ref(text, ref):
    while True:
        m = ref_marker_pos(text, ref)
        if m < 0:
            return text
        i = text.rfind('(footprint ', 0, m)
        if i < 0:
            raise RuntimeError(f'footprint start not found for {ref}')
        j = balanced_block(text, i)
        text = text[:i] + text[j:]


def move_ref(text, ref, x, y, rot=0):
    m = ref_marker_pos(text, ref)
    if m < 0:
        raise RuntimeError(f'{ref} not found')
    i = text.rfind('(footprint ', 0, m)
    j = balanced_block(text, i)
    b = text[i:j]
    rel = m - i
    pre, post = b[:rel], b[rel:]
    repl = f'(at {x:g} {y:g}' + (f' {rot:g}' if rot else '') + ')'
    pre, n = re.subn(r'\(at\s+[-+0-9.]+\s+[-+0-9.]+(?:\s+[-+0-9.]+)?\)', repl, pre, count=1)
    if n != 1:
        raise RuntimeError(f'placement not replaced for {ref}')
    return text[:i] + pre + post + text[j:]


def block_net(b):
    m = re.search(r'\(net(?:\s+\d+)?\s+"([^"]+)"\)', b)
    if m:
        return m.group(1)
    m = re.search(r'\(net\s+(\d+)\)', b)
    return id_net.get(int(m.group(1))) if m else None


def block_layer(b):
    m = re.search(r'\(layer\s+"([^"]+)"\)', b)
    return m.group(1) if m else None


def block_points(b):
    return [(float(x), float(y)) for x, y in re.findall(
        r'\((?:start|end|at)\s+([-+0-9.]+)\s+([-+0-9.]+)', b)]


def remove_blocks(text, token, pred):
    ranges = []
    pos = 0
    needle = '(' + token
    while True:
        i = text.find(needle, pos)
        if i < 0:
            break
        j = balanced_block(text, i)
        b = text[i:j]
        if pred(b):
            ranges.append((i, j))
        pos = j
    for i, j in reversed(ranges):
        text = text[:i] + text[j:]
    return text


# Recreate J3 as twelve *physical* PCB lands. The previous model duplicated
# electrically common contact names at the same coordinates, which is useful
# schematically but wrong for board-level DRC.
s = remove_ref(s, 'J3')

# Link-side test pads are redundant once the production USB-C is fitted. The
# Core USB test pads remain untouched.
for ref in ('TP_LINK_DM', 'TP_LINK_DP'):
    s = remove_ref(s, ref)

# Give the service button and its pull-up a clean mechanical area above J3.
s = move_ref(s, 'SW1', 96.0, 16.5, 0)
s = move_ref(s, 'R30', 94.0, 20.5, 0)

# These local nets are rebuilt completely; doing so also removes every route
# generated by v2/v3 regardless of whether the file still stores a numeric or
# named net reference at this stage.
for net in ('USB_D-_LINK', 'USB_D+_LINK', 'LINK_BOOT', 'ACC_RAW',
            'CORE_TO_LINK', 'LINK_TO_CORE_MCU'):
    s = remove_blocks(s, 'segment', lambda b, n=net: block_net(b) == n)
    s = remove_blocks(s, 'via', lambda b, n=net: block_net(b) == n)

# Replace only the right-edge 3V3_LINK tail feeding R30. The main switched 3V3
# trunk and its via at (93.5,22.8) remain frozen.
s = remove_blocks(
    s, 'segment',
    lambda b: block_net(b) == '3V3_LINK' and block_layer(b) == 'F.Cu'
    and block_points(b) and max(x for x, _ in block_points(b)) >= 93.0
    and any(18.0 <= y <= 24.0 for _, y in block_points(b))
)


def seg(net, layer, x1, y1, x2, y2, w=.20):
    return (f'  (segment (start {x1:.3f} {y1:.3f}) (end {x2:.3f} {y2:.3f}) '
            f'(width {w:.3f}) (layer "{layer}") (net "{net}"))')


def via(net, x, y, size=.55, drill=.30):
    return (f'  (via (at {x:.3f} {y:.3f}) (size {size:.3f}) (drill {drill:.3f}) '
            f'(layers "F.Cu" "B.Cu") (net "{net}"))')


def fp_begin(name, ref, value, x, y, rot=0):
    rr = f' {rot:g}' if rot else ''
    return [
        f'  (footprint "TruckBox:{name}" (layer "F.Cu")',
        f'    (at {x:g} {y:g}{rr})',
        '    (attr smd)',
        f'    (fp_text reference "{ref}" (at 0 -5.5 {rot:g}) (layer "F.SilkS") hide (effects (font (size 0.8 0.8) (thickness 0.12))))',
        f'    (fp_text value "{value}" (at 0 5 {rot:g}) (layer "F.Fab") hide (effects (font (size 0.7 0.7) (thickness 0.1))))',
    ]


def smd_pad(num, x, y, sx, sy, net=None, zone_solid=False):
    nn = f' (net "{net}")' if net else ''
    zc = ' (zone_connect 2)' if zone_solid else ''
    return (f'    (pad "{num}" smd roundrect (at {x:g} {y:g} 90) (size {sx:g} {sy:g}) '
            f'(layers "F.Cu" "F.Paste" "F.Mask") (roundrect_rratio 0.25){zc}{nn})')


def j3_usb4105():
    z = fp_begin('USB_C_Receptacle_GCT_USB4105_16P', 'J3',
                 'USB4105-GF-A-060', 96.325, 28.600, 90)
    z += [
        # Official mechanical envelope / PCB-edge datum.
        '    (fp_line (start 5 3.675) (end -5 3.675) (stroke (width 0.1) (type solid)) (layer "Dwgs.User"))',
        '    (fp_rect (start -5.32 -4.76) (end 5.32 4.18) (stroke (width 0.05) (type solid)) (fill none) (layer "F.CrtYd"))',
        '    (fp_rect (start -4.47 -3.675) (end 4.47 3.675) (stroke (width 0.10) (type solid)) (fill none) (layer "F.Fab"))',

        # Twelve physical solder lands. VBUS/SBU are intentionally NC because
        # USB VBUS must never power the TruckBox or back-feed 3V3_LINK.
        # The two end GND lands retain the specified width but use a 1.00 mm
        # inward land length, providing >= board drill-to-copper clearance to
        # the connector's mandatory locating pegs.
        smd_pad('1',  -3.20, -3.68, .60, 1.00, 'GND', True),
        smd_pad('2',  -2.40, -3.68, .60, 1.15, None),
        smd_pad('3',  -1.75, -3.68, .30, 1.15, None),
        smd_pad('4',  -1.25, -3.68, .30, 1.15, 'USB_CC1'),
        smd_pad('5',  -0.75, -3.68, .30, 1.15, 'USB_D-_LINK'),
        smd_pad('6',  -0.25, -3.68, .30, 1.15, 'USB_D+_LINK'),
        smd_pad('7',   0.25, -3.68, .30, 1.15, 'USB_D-_LINK'),
        smd_pad('8',   0.75, -3.68, .30, 1.15, 'USB_D+_LINK'),
        smd_pad('9',   1.25, -3.68, .30, 1.15, None),
        smd_pad('10',  1.75, -3.68, .30, 1.15, 'USB_CC2'),
        smd_pad('11',  2.40, -3.68, .60, 1.15, None),
        smd_pad('12',  3.20, -3.68, .60, 1.00, 'GND', True),

        # Mandatory plastic locating pegs and four shield stakes.
        '    (pad "" np_thru_hole circle (at -2.89 -2.605) (size 0.65 0.65) (drill 0.65) (layers "*.Cu" "*.Mask"))',
        '    (pad "" np_thru_hole circle (at 2.89 -2.605) (size 0.65 0.65) (drill 0.65) (layers "*.Cu" "*.Mask"))',
        '    (pad "SH" thru_hole oval (at -4.32 -3.105 90) (size 1 2.1) (drill oval 0.6 1.7) (layers "*.Cu" "*.Mask" "F.Paste") (zone_connect 2) (net "GND"))',
        '    (pad "SH" thru_hole oval (at -4.32 1.075 90) (size 1 1.8) (drill oval 0.6 1.4) (layers "*.Cu" "*.Mask" "F.Paste") (zone_connect 2) (net "GND"))',
        '    (pad "SH" thru_hole oval (at 4.32 -3.105 90) (size 1 2.1) (drill oval 0.6 1.7) (layers "*.Cu" "*.Mask" "F.Paste") (zone_connect 2) (net "GND"))',
        '    (pad "SH" thru_hole oval (at 4.32 1.075 90) (size 1 1.8) (drill oval 0.6 1.4) (layers "*.Cu" "*.Mask" "F.Paste") (zone_connect 2) (net "GND"))',
        '  )',
    ]
    return z


r = [
    # --- R30 / SW1 service BOOT block ---
    # R30 pad1 = 3V3_LINK at (93.5,20.5); pad2 = LINK_BOOT at (94.5,20.5).
    seg('3V3_LINK', 'F.Cu', 93.50,22.80,93.50,20.50,.22),
    # Escape U2 pin15 away from J3's upper shield stake, change layer above it,
    # return to F.Cu below the 3V3 tail, then enter R30 pad2 from the left.
    seg('LINK_BOOT','F.Cu',90.75,24.45,91.55,24.45,.20),
    seg('LINK_BOOT','F.Cu',91.55,24.45,92.00,22.00,.20),
    via('LINK_BOOT',92.00,22.00),
    seg('LINK_BOOT','B.Cu',92.00,22.00,92.00,19.50,.20),
    via('LINK_BOOT',92.00,19.50),
    seg('LINK_BOOT','F.Cu',92.00,19.50,94.50,19.50,.20),
    seg('LINK_BOOT','F.Cu',94.50,19.50,94.50,20.50,.20),
    # Same net continues upward to the relocated service switch pad1.
    seg('LINK_BOOT','F.Cu',94.50,20.50,94.50,16.50,.20),

    # --- CORE_TO_LINK UART ---
    # The long run remains on In2; only the final right-side escape uses B.Cu.
    # Vias are below/outside U2, not under the ESP32 module.
    seg('CORE_TO_LINK','F.Cu',39.50,28.00,39.50,30.00,.20),
    via('CORE_TO_LINK',39.50,30.00),
    seg('CORE_TO_LINK','In2.Cu',39.50,30.00,40.50,31.00,.20),
    seg('CORE_TO_LINK','In2.Cu',40.50,31.00,88.50,31.00,.20),
    seg('CORE_TO_LINK','In2.Cu',88.50,31.00,88.50,33.30,.20),
    via('CORE_TO_LINK',88.50,33.30),
    seg('CORE_TO_LINK','B.Cu',88.50,33.30,88.50,16.83,.20),
    seg('CORE_TO_LINK','B.Cu',88.50,16.83,92.00,16.83,.20),
    via('CORE_TO_LINK',92.00,16.83),
    seg('CORE_TO_LINK','F.Cu',92.00,16.83,90.75,16.83,.20),

    # --- LINK_TO_CORE_MCU UART ---
    seg('LINK_TO_CORE_MCU','F.Cu',42.50,28.00,42.50,26.00,.20),
    via('LINK_TO_CORE_MCU',42.50,26.00),
    seg('LINK_TO_CORE_MCU','In2.Cu',42.50,26.00,42.50,29.10,.20),
    seg('LINK_TO_CORE_MCU','In2.Cu',42.50,29.10,89.30,29.10,.20),
    seg('LINK_TO_CORE_MCU','In2.Cu',89.30,29.10,89.30,34.00,.20),
    via('LINK_TO_CORE_MCU',89.30,34.00),
    seg('LINK_TO_CORE_MCU','B.Cu',89.30,34.00,89.30,18.10,.20),
    seg('LINK_TO_CORE_MCU','B.Cu',89.30,18.10,92.00,18.10,.20),
    via('LINK_TO_CORE_MCU',92.00,18.10),
    seg('LINK_TO_CORE_MCU','F.Cu',92.00,18.10,90.75,18.10,.20),

    # --- ACC_RAW ---
    # Leave R10 to the left, change layer before the divider network, then run
    # below the USB connector; this avoids ACC_MID1 and the GND stitch at94,36.
    seg('ACC_RAW','F.Cu',91.50,35.00,90.50,35.00,.28),
    via('ACC_RAW',90.50,35.00),
    seg('ACC_RAW','B.Cu',90.50,35.00,96.00,35.00,.28),
    via('ACC_RAW',96.00,35.00),
    seg('ACC_RAW','F.Cu',96.00,35.00,96.00,45.50,.28),
    seg('ACC_RAW','F.Cu',96.00,45.50,97.80,45.50,.28),

    # --- Main USB pair from R42/R43 to the connector breakout ---
    # D+ remains on F.Cu. D- changes to B.Cu only for a short launch below the
    # existing MCU-side USB routes, then both form a parallel lower-edge pair.
    seg('USB_D+_LINK','F.Cu',68.50,25.00,68.80,25.00,.20),
    seg('USB_D+_LINK','F.Cu',68.80,25.00,68.80,31.40,.20),
    seg('USB_D+_LINK','F.Cu',68.80,31.40,90.80,31.40,.20),

    seg('USB_D-_LINK','F.Cu',68.50,23.00,69.60,23.00,.20),
    seg('USB_D-_LINK','F.Cu',69.60,23.00,69.60,30.60,.20),
    seg('USB_D-_LINK','F.Cu',69.60,30.60,72.80,30.60,.20),
    via('USB_D-_LINK',72.80,30.60),
    seg('USB_D-_LINK','B.Cu',72.80,30.60,72.80,32.20,.20),
    via('USB_D-_LINK',72.80,32.20),
    seg('USB_D-_LINK','F.Cu',72.80,32.20,90.80,32.20,.20),

    # --- Four-contact USB-C fanout ---
    # Four 0.20 mm tracks fan monotonically downward to four 0.55/0.30 vias.
    # The 0.80 mm via pitch gives 0.25 mm copper gap, exceeding the board's
    # 0.20 mm minimum. Same-net pairs are merged on B.Cu away from U2/J3.
    # Top-to-bottom pad order at J3 is D+, D-, D+, D-.
    seg('USB_D+_LINK','F.Cu',92.645,27.850,90.800,29.800,.20),
    via('USB_D+_LINK',90.800,29.800),
    seg('USB_D-_LINK','F.Cu',92.645,28.350,90.800,30.600,.20),
    via('USB_D-_LINK',90.800,30.600),
    seg('USB_D+_LINK','F.Cu',92.645,28.850,90.800,31.400,.20),
    via('USB_D+_LINK',90.800,31.400),
    seg('USB_D-_LINK','F.Cu',92.645,29.350,90.800,32.200,.20),
    via('USB_D-_LINK',90.800,32.200),

    # D+ merge to the right; D- merge to the left. These trunks remain clear
    # of the two UART B.Cu lanes at x=88.5/89.3.
    seg('USB_D+_LINK','B.Cu',90.80,29.80,91.60,29.80,.20),
    seg('USB_D+_LINK','B.Cu',91.60,29.80,91.60,31.40,.20),
    seg('USB_D+_LINK','B.Cu',91.60,31.40,90.80,31.40,.20),
    seg('USB_D-_LINK','B.Cu',90.80,30.60,90.00,30.60,.20),
    seg('USB_D-_LINK','B.Cu',90.00,30.60,90.00,32.20,.20),
    seg('USB_D-_LINK','B.Cu',90.00,32.20,90.80,32.20,.20),
]

r += j3_usb4105()
pos = s.rfind('\n)')
if pos < 0:
    raise RuntimeError('final PCB paren not found')
s = s[:pos] + '\n' + '\n'.join(r) + s[pos:]
P.write_text(s, encoding='utf-8')
print(f'Applied USB-C production cleanup v4 to {P}')
